"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleAlert, Plus, RefreshCcw, Search, ShieldAlert, X } from "lucide-react";
import type { Rider, RiderViolationRecord } from "@/types";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { cn } from "@/utils/cn";

type ApiResponse = { success: boolean; can_edit?: boolean; violations?: RiderViolationRecord[]; violation?: RiderViolationRecord; error?: string; result?: { attendanceUpdated: number; violationsCreated: number } };
const initialForm = { rider_id: "", work_date: today(), violation_type: "POLICY", severity: "MEDIUM", zone: "", note: "" };

export function ViolationsView() {
  const [violations, setViolations] = useState<RiderViolationRecord[]>([]); const [riders, setRiders] = useState<Rider[]>([]); const [canEdit, setCanEdit] = useState(false); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); const [response, riderResult] = await Promise.all([fetch("/api/violations", { cache: "no-store" }), createClient().from("riders").select("*").eq("status", "active").order("full_name")]); const result = await response.json().catch(() => null) as ApiResponse | null; if (!response.ok || !result?.success) setError(result?.error ?? "Không thể tải vi phạm"); else { setViolations(result.violations ?? []); setCanEdit(Boolean(result.can_edit)); } if (!riderResult.error) setRiders((riderResult.data ?? []) as Rider[]); setLoading(false); }, []);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return violations.filter((item) => (!normalized || `${item.rider_name} ${item.rider_code} ${item.zone} ${item.note}`.toLowerCase().includes(normalized)) && (status === "all" || item.status === status) && (type === "all" || item.violation_type === type)); }, [query, status, type, violations]);
  const stats = useMemo(() => ({ total: violations.length, open: violations.filter((item) => item.status === "OPEN").length, high: violations.filter((item) => item.severity === "HIGH" && item.status === "OPEN").length, resolved: violations.filter((item) => item.status === "RESOLVED").length }), [violations]);
  async function addViolation(event: React.FormEvent) { event.preventDefault(); const rider = riders.find((item) => item.id === form.rider_id); if (!rider) return; setSaving(true); const response = await fetch("/api/violations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, rider_id: rider.id, rider_code: rider.rider_code, rider_name: rider.full_name, zone: form.zone || rider.delivery_district }) }); const result = await response.json().catch(() => null) as ApiResponse | null; setSaving(false); if (!response.ok || !result?.success) return setError(result?.error ?? "Không thể thêm vi phạm"); setShowForm(false); setForm(initialForm); setSuccess("Đã thêm vi phạm."); await load(); }
  async function toggleResolved(item: RiderViolationRecord) { const next = item.status === "OPEN" ? "RESOLVED" : "OPEN"; const note = next === "RESOLVED" ? window.prompt("Ghi chú xử lý (không bắt buộc):", item.resolution_note ?? "") : null; const response = await fetch("/api/violations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id, status: next, resolution_note: note }) }); const result = await response.json().catch(() => null) as ApiResponse | null; if (!response.ok || !result?.violation) return setError(result?.error ?? "Không thể cập nhật"); setViolations((current) => current.map((value) => value.id === item.id ? result.violation! : value)); }
  async function reconcile() { setSaving(true); const response = await fetch("/api/violations/reconcile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ work_date: today() }) }); const result = await response.json().catch(() => null) as ApiResponse | null; setSaving(false); if (!response.ok || !result?.success) return setError(result?.error ?? "Đối soát thất bại"); setSuccess(`Đã cập nhật ${result.result?.attendanceUpdated ?? 0} lịch và tạo ${result.result?.violationsCreated ?? 0} vi phạm.`); await load(); }
  return <div className="mx-auto max-w-[1600px] space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-red-600">Safety & compliance</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Quản lý vi phạm rider</h1><p className="mt-1 text-sm text-slate-500">Theo dõi, thêm mới và xác nhận xử lý vi phạm vận hành.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCcw size={16} className={loading ? "animate-spin" : undefined} />Tải lại</Button>{canEdit ? <><Button type="button" variant="secondary" onClick={() => void reconcile()} disabled={saving}>Đối soát hôm nay</Button><Button type="button" onClick={() => setShowForm(true)}><Plus size={16} />Thêm vi phạm</Button></> : null}</div></header>
  {error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}{success ? <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{success}</p> : null}
  <section className="grid grid-cols-2 gap-4 xl:grid-cols-4"><Kpi label="Tổng vi phạm" value={stats.total} icon={<ShieldAlert size={18} />} /><Kpi label="Chưa xử lý" value={stats.open} icon={<CircleAlert size={18} />} tone="red" /><Kpi label="Mức cao đang mở" value={stats.high} icon={<CircleAlert size={18} />} tone="amber" /><Kpi label="Đã xử lý" value={stats.resolved} icon={<CheckCircle2 size={18} />} tone="green" /></section>
  <section className="rounded-xl border border-slate-200 bg-white"><div className="grid gap-3 border-b border-slate-200 p-4 md:grid-cols-[1fr_180px_220px]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><Input className="pl-9" placeholder="Tìm rider, mã, khu vực, ghi chú" value={query} onChange={(event) => setQuery(event.target.value)} /></label><Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Mọi trạng thái</option><option value="OPEN">Chưa xử lý</option><option value="RESOLVED">Đã xử lý</option></Select><Select value={type} onChange={(event) => setType(event.target.value)}><option value="all">Mọi loại vi phạm</option>{violationOptions().map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</Select></div><div className="max-h-[680px] min-h-[400px] overflow-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-xs text-slate-600 shadow-[0_1px_0_#e2e8f0]"><tr><th className="px-4 py-3">Rider</th><th className="px-4 py-3">Ngày</th><th className="px-4 py-3">Loại</th><th className="px-4 py-3">Mức độ</th><th className="px-4 py-3">Khu vực</th><th className="px-4 py-3">Ghi chú</th><th className="px-4 py-3">Trạng thái</th><th /></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-4 py-3"><p className="font-semibold text-slate-900">{item.rider_name ?? item.rider_code}</p><p className="text-xs text-slate-500">{item.rider_code}</p></td><td className="px-4 py-3 tabular-nums">{formatDate(item.work_date)}</td><td className="px-4 py-3 font-medium">{typeLabel(item.violation_type)}</td><td className="px-4 py-3"><Severity value={item.severity} /></td><td className="px-4 py-3">{item.zone ?? "—"}</td><td className="max-w-72 px-4 py-3"><p className="line-clamp-2 text-slate-600" title={item.note ?? ""}>{item.note ?? "—"}</p></td><td className="px-4 py-3"><Status value={item.status} /></td><td className="px-4 py-3 text-right">{canEdit ? <Button type="button" variant="ghost" className="h-9" onClick={() => void toggleResolved(item)}>{item.status === "OPEN" ? "Đánh dấu xử lý" : "Mở lại"}</Button> : null}</td></tr>)}{!loading && filtered.length === 0 ? <tr><td colSpan={8} className="h-72 text-center text-slate-500">Không có vi phạm phù hợp.</td></tr> : null}</tbody></table></div></section>
  {showForm ? <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/35 sm:place-items-center sm:p-4"><button type="button" className="absolute inset-0" aria-label="Đóng" onClick={() => setShowForm(false)} /><form onSubmit={addViolation} className="relative z-10 w-full max-w-xl space-y-4 rounded-t-2xl bg-white p-5 shadow-xl sm:rounded-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Thêm vi phạm</h2><Button type="button" variant="ghost" className="size-9 p-0" onClick={() => setShowForm(false)}><X size={17} /></Button></div><Field label="Rider"><Select required value={form.rider_id} onChange={(event) => setForm((current) => ({ ...current, rider_id: event.target.value }))}><option value="">Chọn rider</option>{riders.map((rider) => <option key={rider.id} value={rider.id}>{rider.full_name ?? rider.rider_code} · {rider.rider_code}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Ngày"><Input required type="date" value={form.work_date} onChange={(event) => setForm((current) => ({ ...current, work_date: event.target.value }))} /></Field><Field label="Mức độ"><Select value={form.severity} onChange={(event) => setForm((current) => ({ ...current, severity: event.target.value }))}><option value="LOW">Thấp</option><option value="MEDIUM">Vừa</option><option value="HIGH">Cao</option></Select></Field></div><Field label="Loại"><Select value={form.violation_type} onChange={(event) => setForm((current) => ({ ...current, violation_type: event.target.value }))}>{violationOptions().map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field><Field label="Ghi chú"><textarea className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm" value={form.note} onChange={(event) => setForm((current) => ({ ...current, note: event.target.value }))} /></Field><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Hủy</Button><Button type="submit" disabled={saving}>{saving ? "Đang lưu..." : "Lưu vi phạm"}</Button></div></form></div> : null}</div>;
}

function Kpi({ label, value, icon, tone = "slate" }: { label: string; value: number; icon: React.ReactNode; tone?: "slate" | "red" | "amber" | "green" }) { const styles = { slate: "bg-slate-100 text-slate-700", red: "bg-red-50 text-red-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700" }; return <article className="min-h-28 rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold tabular-nums">{value}</p></div><span className={cn("grid size-9 place-items-center rounded-lg", styles[tone])}>{icon}</span></div></article>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function Severity({ value }: { value: RiderViolationRecord["severity"] }) { const style = value === "HIGH" ? "bg-red-50 text-red-700" : value === "MEDIUM" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"; return <span className={cn("rounded-full px-2 py-1 text-xs font-semibold", style)}>{value === "HIGH" ? "Cao" : value === "MEDIUM" ? "Vừa" : "Thấp"}</span>; }
function Status({ value }: { value: RiderViolationRecord["status"] }) { return <span className={cn("rounded-full px-2 py-1 text-xs font-semibold", value === "RESOLVED" ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700")}>{value === "RESOLVED" ? "Đã xử lý" : "Chưa xử lý"}</span>; }
function violationOptions() { return [{ value: "LATE_CHECKIN", label: "Đi trễ" }, { value: "NO_SHOW", label: "Vắng ca" }, { value: "SLA_BREACH", label: "Vi phạm SLA" }, { value: "SAFETY", label: "An toàn" }, { value: "POLICY", label: "Chính sách" }, { value: "OFF_UNEXPECTED", label: "OFF đột xuất" }, { value: "WORKING_REST_DAY", label: "OFF nhưng không OFF" }]; }
function typeLabel(value: RiderViolationRecord["violation_type"]) { return violationOptions().find((item) => item.value === value)?.label ?? value; }
function formatDate(value: string) { return new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
