"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronRight, ShieldAlert, X } from "lucide-react";
import { Select } from "@/components/ui/select";
import { cn } from "@/utils/cn";

export type RiderViolation = {
  id: string;
  riderId: string;
  riderCode: string;
  riderName: string;
  violationType: "LATE_CHECKIN" | "NO_SHOW" | "SLA_BREACH" | "SAFETY" | "POLICY";
  severity: "LOW" | "MEDIUM" | "HIGH";
  zone: string;
  occurredAt: string;
  note?: string;
};

type RangeKey = "LAST_7_DAYS" | "LAST_30_DAYS" | "THIS_WEEK" | "LAST_WEEK";

export function WeeklyRiderViolationsCard({ violations, defaultRange = "LAST_7_DAYS", className }: { violations: RiderViolation[]; defaultRange?: RangeKey; className?: string }) {
  const [range, setRange] = useState<RangeKey>(defaultRange);
  const [zone, setZone] = useState("all");
  const [severity, setSeverity] = useState<"all" | "HIGH">("all");
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [selectedRider, setSelectedRider] = useState<string | null>(null);
  const zones = useMemo(() => Array.from(new Set(violations.map((item) => item.zone).filter(Boolean))).sort((a, b) => a.localeCompare(b, "vi", { numeric: true })), [violations]);
  const period = useMemo(() => rangePeriod(range), [range]);
  const previousPeriod = useMemo(() => previousRange(period), [period]);
  const filtered = useMemo(() => violations.filter((item) => inPeriod(item.occurredAt, period) && (zone === "all" || item.zone === zone) && (severity === "all" || item.severity === severity) && (!selectedDate || item.occurredAt.slice(0, 10) === selectedDate)), [period, selectedDate, severity, violations, zone]);
  const previous = useMemo(() => violations.filter((item) => inPeriod(item.occurredAt, previousPeriod) && (zone === "all" || item.zone === zone) && (severity === "all" || item.severity === severity)), [previousPeriod, severity, violations, zone]);
  const summary = useMemo(() => summarize(filtered, previous), [filtered, previous]);
  const daily = useMemo(() => dailySummary(filtered, period), [filtered, period]);
  const topRiders = useMemo(() => topViolators(filtered), [filtered]);
  const drawerEvents = useMemo(() => selectedRider ? filtered.filter((item) => item.riderId === selectedRider).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)) : [], [filtered, selectedRider]);
  const max = Math.max(1, ...daily.map((item) => item.total));

  return <section className={cn("overflow-hidden rounded-xl border border-slate-200 bg-white", className)}>
    <div className="flex flex-col gap-4 border-b border-slate-200 p-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-red-600" /><h2 className="font-semibold text-slate-950">Weekly Rider Violations</h2></div><p className="mt-1 text-sm text-slate-500">Theo dõi vi phạm SLA và chấm công có dữ liệu xác thực.</p></div><div className="grid gap-2 sm:grid-cols-3"><Select value={range} onChange={(event) => { setRange(event.target.value as RangeKey); setSelectedDate(null); }} aria-label="Thời gian vi phạm"><option value="LAST_7_DAYS">7 ngày gần nhất</option><option value="LAST_30_DAYS">30 ngày gần nhất</option><option value="THIS_WEEK">Tuần này</option><option value="LAST_WEEK">Tuần trước</option></Select><Select value={zone} onChange={(event) => setZone(event.target.value)} aria-label="Khu vực vi phạm"><option value="all">Tất cả khu vực</option>{zones.map((item) => <option key={item} value={item}>{item}</option>)}</Select><Select value={severity} onChange={(event) => setSeverity(event.target.value as "all" | "HIGH")} aria-label="Mức độ vi phạm"><option value="all">Mọi mức độ</option><option value="HIGH">Chỉ mức cao</option></Select></div></div>
    <div className="grid grid-cols-2 gap-px border-b border-slate-200 bg-slate-200 sm:grid-cols-4"><ViolationKpi label="Tổng vi phạm" value={summary.total} context={selectedDate ? formatDate(selectedDate) : rangeLabel(range)} /><ViolationKpi label="Rider liên quan" value={summary.riders} context="Rider duy nhất" /><ViolationKpi label="Mức độ cao" value={summary.high} context={`${summary.medium} mức vừa`} /><ViolationKpi label="So với kỳ trước" value={`${summary.change >= 0 ? "+" : ""}${summary.change.toFixed(0)}%`} context={`${previous.length} vi phạm kỳ trước`} tone={summary.change > 0 ? "red" : "green"} /></div>
    <div className="grid grid-cols-12 gap-5 p-4">
      <article className="col-span-12 lg:col-span-7"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-slate-900">Vi phạm theo ngày</h3><p className="mt-0.5 text-xs text-slate-500">Chọn một cột để lọc danh sách rider.</p></div>{selectedDate ? <button type="button" className="text-xs font-semibold text-blue-700" onClick={() => setSelectedDate(null)}>Bỏ lọc ngày</button> : null}</div><div className="mt-5 flex h-44 items-end gap-1.5 border-b border-slate-200 px-1">{daily.map((item) => <button key={item.date} type="button" title={`${formatDate(item.date)}: ${item.total} vi phạm · Cao ${item.high}, Vừa ${item.medium}, Thấp ${item.low}`} onClick={() => setSelectedDate((current) => current === item.date ? null : item.date)} className={cn("group flex h-full min-w-0 flex-1 flex-col justify-end rounded-t transition hover:bg-slate-50", selectedDate === item.date && "bg-blue-50")}><span className="mb-1 text-[10px] font-semibold tabular-nums text-slate-600">{item.total || ""}</span><span className="mx-auto flex w-full max-w-9 flex-col justify-end overflow-hidden rounded-t" style={{ height: `${Math.max(item.total ? 5 : 0, item.total / max * 78)}%` }}><span className="bg-slate-400" style={{ height: `${item.total ? item.low / item.total * 100 : 0}%` }} /><span className="bg-amber-500" style={{ height: `${item.total ? item.medium / item.total * 100 : 0}%` }} /><span className="bg-red-500" style={{ height: `${item.total ? item.high / item.total * 100 : 0}%` }} /></span><span className="mt-2 truncate text-[9px] text-slate-400 sm:text-[10px]">{item.date.slice(8, 10)}/{item.date.slice(5, 7)}</span></button>)}</div><div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-600"><Legend color="bg-red-500" label="Cao" /><Legend color="bg-amber-500" label="Vừa" /><Legend color="bg-slate-400" label="Thấp" /></div></article>
      <article className="col-span-12 lg:col-span-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-slate-900">Rider có nhiều vi phạm</h3><p className="mt-0.5 text-xs text-slate-500">Top 5 trong phạm vi lọc.</p></div><Link href="/violations" className="flex items-center gap-1 text-xs font-semibold text-blue-700">Xem tất cả<ChevronRight size={14} /></Link></div><div className="mt-3 divide-y divide-slate-100">{topRiders.map((rider) => <button key={rider.id} type="button" className="flex w-full items-center gap-3 py-3 text-left hover:bg-slate-50" onClick={() => setSelectedRider(rider.id)}><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{rider.name}</p><p className="truncate text-xs text-slate-500">{rider.code} · {typeLabel(rider.commonType)}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">{rider.total}</span>{rider.high > 0 ? <span className="rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-700">{rider.high} cao</span> : null}</button>)}{topRiders.length === 0 ? <p className="py-8 text-center text-sm text-slate-500">Không có vi phạm trong phạm vi này.</p> : null}</div></article>
    </div>
    {selectedRider ? <><button type="button" aria-label="Đóng lịch sử vi phạm" className="fixed inset-0 z-40 bg-slate-950/20" onClick={() => setSelectedRider(null)} /><aside role="dialog" aria-modal="true" aria-labelledby="violation-history-title" className="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto border-l border-slate-200 bg-white p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-red-600">Compliance history</p><h2 id="violation-history-title" className="mt-1 text-xl font-bold text-slate-950">{drawerEvents[0]?.riderName}</h2><p className="text-sm text-slate-500">{drawerEvents.length} vi phạm trong phạm vi lọc</p></div><button type="button" aria-label="Đóng" className="grid size-9 place-items-center rounded-lg bg-slate-100" onClick={() => setSelectedRider(null)}><X size={17} /></button></div><div className="mt-6 space-y-3">{drawerEvents.map((event) => <div key={event.id} className="rounded-lg border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><SeverityBadge severity={event.severity} /><span className="text-xs text-slate-500">{formatDateTime(event.occurredAt)}</span></div><p className="mt-2 font-semibold text-slate-900">{typeLabel(event.violationType)}</p><p className="mt-1 text-sm text-slate-500">{event.note ?? event.zone}</p></div>)}</div></aside></> : null}
  </section>;
}

function ViolationKpi({ label, value, context, tone = "slate" }: { label: string; value: number | string; context: string; tone?: "slate" | "red" | "green" }) { return <div className="min-h-24 bg-white p-4"><p className="text-xs font-medium text-slate-500">{label}</p><p className={cn("mt-1 text-xl font-bold tabular-nums", tone === "red" ? "text-red-700" : tone === "green" ? "text-emerald-700" : "text-slate-950")}>{value}</p><p className="mt-1 text-[11px] text-slate-400">{context}</p></div>; }
function Legend({ color, label }: { color: string; label: string }) { return <span className="flex items-center gap-1.5"><span className={cn("size-2 rounded-sm", color)} />{label}</span>; }
function SeverityBadge({ severity }: { severity: RiderViolation["severity"] }) { const style = severity === "HIGH" ? "bg-red-50 text-red-700" : severity === "MEDIUM" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"; return <span className={cn("rounded-full px-2 py-1 text-[10px] font-bold", style)}>{severity === "HIGH" ? "Cao" : severity === "MEDIUM" ? "Vừa" : "Thấp"}</span>; }
function summarize(current: RiderViolation[], previous: RiderViolation[]) { return { total: current.length, riders: new Set(current.map((item) => item.riderId)).size, high: current.filter((item) => item.severity === "HIGH").length, medium: current.filter((item) => item.severity === "MEDIUM").length, change: previous.length ? (current.length - previous.length) / previous.length * 100 : current.length ? 100 : 0 }; }
function dailySummary(items: RiderViolation[], period: { start: string; end: string }) { const dates: string[] = []; const current = new Date(`${period.start}T00:00:00Z`); const end = new Date(`${period.end}T00:00:00Z`); while (current <= end) { dates.push(current.toISOString().slice(0, 10)); current.setUTCDate(current.getUTCDate() + 1); } const map = new Map<string, RiderViolation[]>(); for (const item of items) { const date = item.occurredAt.slice(0, 10); map.set(date, [...(map.get(date) ?? []), item]); } return dates.map((date) => { const events = map.get(date) ?? []; return { date, total: events.length, high: events.filter((item) => item.severity === "HIGH").length, medium: events.filter((item) => item.severity === "MEDIUM").length, low: events.filter((item) => item.severity === "LOW").length }; }); }
function topViolators(items: RiderViolation[]) { const map = new Map<string, RiderViolation[]>(); for (const item of items) map.set(item.riderId, [...(map.get(item.riderId) ?? []), item]); return Array.from(map, ([id, events]) => { const types = new Map<RiderViolation["violationType"], number>(); for (const event of events) types.set(event.violationType, (types.get(event.violationType) ?? 0) + 1); return { id, code: events[0]!.riderCode, name: events[0]!.riderName, total: events.length, high: events.filter((item) => item.severity === "HIGH").length, commonType: [...types.entries()].sort((a, b) => b[1] - a[1])[0]![0] }; }).sort((a, b) => b.total - a.total || b.high - a.high).slice(0, 5); }
function rangePeriod(range: RangeKey) { const today = todayDate(); if (range === "LAST_7_DAYS") return { start: shiftDate(today, -6), end: today }; if (range === "LAST_30_DAYS") return { start: shiftDate(today, -29), end: today }; const monday = startOfWeek(today); if (range === "THIS_WEEK") return { start: monday, end: today }; return { start: shiftDate(monday, -7), end: shiftDate(monday, -1) }; }
function previousRange(period: { start: string; end: string }) { const days = Math.round((new Date(`${period.end}T00:00:00Z`).getTime() - new Date(`${period.start}T00:00:00Z`).getTime()) / 86400000) + 1; return { start: shiftDate(period.start, -days), end: shiftDate(period.start, -1) }; }
function inPeriod(value: string, period: { start: string; end: string }) { const date = value.slice(0, 10); return date >= period.start && date <= period.end; }
function startOfWeek(value: string) { const date = new Date(`${value}T00:00:00Z`); const day = date.getUTCDay() || 7; date.setUTCDate(date.getUTCDate() - day + 1); return date.toISOString().slice(0, 10); }
function shiftDate(value: string, days: number) { const date = new Date(`${value}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function todayDate() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function rangeLabel(range: RangeKey) { return range === "LAST_7_DAYS" ? "7 ngày gần nhất" : range === "LAST_30_DAYS" ? "30 ngày gần nhất" : range === "THIS_WEEK" ? "Tuần này" : "Tuần trước"; }
function typeLabel(type: RiderViolation["violationType"]) { return ({ LATE_CHECKIN: "Đi trễ", NO_SHOW: "Vắng ca", SLA_BREACH: "Vi phạm SLA", SAFETY: "An toàn", POLICY: "Chính sách" } as const)[type]; }
function formatDate(value: string) { return new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }
function formatDateTime(value: string) { const date = new Date(value); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Ho_Chi_Minh" }).format(date) : value; }
