import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

const updateSchema = z.object({ rider_id: z.string().uuid(), rider_code: z.string().min(1), work_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), replacement_rider_id: z.string().uuid().nullable(), replacement_rider_code: z.string().nullable(), status: z.enum(["ASSIGNED","MISSING"]), note: z.string().max(500).nullable().optional() });
async function session() { const client = await createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) return null; const admin = createAdminClient(); const { data: profile } = await admin.from("profiles").select("role").eq("id", user.id).maybeSingle(); return { role: profile?.role ?? "viewer", admin }; }
export async function GET(request: Request) { const auth = await session(); if (!auth) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); const url = new URL(request.url); const start = url.searchParams.get("start"); const end = url.searchParams.get("end"); if (!start || !end) return NextResponse.json({ success: false, error: "Thiếu khoảng ngày" }, { status: 400 }); const { data, error } = await auth.admin.from("pickup_replacements").select("*").gte("work_date", start).lte("work_date", end).order("work_date"); if (error) return NextResponse.json({ success: false, error: error.message }, { status: 400 }); return NextResponse.json({ success: true, can_edit: auth.role === "admin" || auth.role === "leader", replacements: data ?? [] }); }
export async function PUT(request: Request) { const auth = await session(); if (!auth) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (auth.role !== "admin" && auth.role !== "leader") return NextResponse.json({ success: false, error: "Không có quyền cập nhật" }, { status: 403 }); const parsed = updateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ success: false, error: "Dữ liệu không hợp lệ" }, { status: 400 }); const { data, error } = await auth.admin.from("pickup_replacements").upsert(parsed.data, { onConflict: "rider_code,work_date" }).select("*").single(); if (error) return NextResponse.json({ success: false, error: error.message }, { status: 400 }); return NextResponse.json({ success: true, replacement: data }); }
