import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { canManageOperations } from "@/lib/auth/permissions";

const createSchema = z.object({ rider_id: z.string().uuid().nullable().optional(), rider_code: z.string().trim().min(1), rider_name: z.string().trim().optional().nullable(), work_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), violation_type: z.enum(["LATE_CHECKIN","NO_SHOW","SLA_BREACH","SAFETY","POLICY","OFF_UNEXPECTED","WORKING_REST_DAY"]), severity: z.enum(["LOW","MEDIUM","HIGH"]), zone: z.string().trim().optional().nullable(), note: z.string().trim().max(1000).optional().nullable() });
const patchSchema = z.object({ id: z.string().uuid(), status: z.enum(["OPEN","RESOLVED"]), resolution_note: z.string().trim().max(1000).optional().nullable() });

async function session() { const client = await createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) return null; const admin = createAdminClient(); const { data: profile } = await admin.from("profiles").select("role").eq("id", user.id).maybeSingle(); return { user, role: profile?.role ?? "viewer", admin }; }

export async function GET(request: Request) { const auth = await session(); if (!auth) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); const url = new URL(request.url); const start = url.searchParams.get("start"); const end = url.searchParams.get("end"); let query = auth.admin.from("rider_violations").select("*").order("work_date", { ascending: false }).order("created_at", { ascending: false }).limit(1000); if (start) query = query.gte("work_date", start); if (end) query = query.lte("work_date", end); const { data, error } = await query; if (error) return NextResponse.json({ success: false, error: error.message }, { status: 400 }); return NextResponse.json({ success: true, can_edit: canManageOperations(auth.role), violations: data ?? [] }); }
export async function POST(request: Request) { const auth = await session(); if (!auth) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (!canManageOperations(auth.role)) return NextResponse.json({ success: false, error: "Không có quyền thêm vi phạm" }, { status: 403 }); const parsed = createSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ success: false, error: "Dữ liệu không hợp lệ", issues: parsed.error.flatten() }, { status: 400 }); const { data, error } = await auth.admin.from("rider_violations").insert({ ...parsed.data, status: "OPEN", source: "manual" }).select("*").single(); if (error) return NextResponse.json({ success: false, error: error.message }, { status: 400 }); return NextResponse.json({ success: true, violation: data }); }
export async function PATCH(request: Request) { const auth = await session(); if (!auth) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 }); if (!canManageOperations(auth.role)) return NextResponse.json({ success: false, error: "Không có quyền xử lý vi phạm" }, { status: 403 }); const parsed = patchSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ success: false, error: "Dữ liệu không hợp lệ" }, { status: 400 }); const resolved = parsed.data.status === "RESOLVED"; const { data, error } = await auth.admin.from("rider_violations").update({ status: parsed.data.status, resolution_note: parsed.data.resolution_note ?? null, resolved_at: resolved ? new Date().toISOString() : null, resolved_by: resolved ? auth.user.id : null }).eq("id", parsed.data.id).select("*").single(); if (error) return NextResponse.json({ success: false, error: error.message }, { status: 400 }); return NextResponse.json({ success: true, violation: data }); }
